config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :workspaces do
    collection do
      get :my_workspaces
    end
  end

  resources :workspaces do
      resources :bookings, only: [:create]
  end



  # resources :bookings, only: [:index]

  resources :bookings, only: [:destroy] do
    member do
      get :validation
      get :rejection
    end

    collection do
      get :my_bookings
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :workspace

  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :workspaces, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # has_many :workspaces, through: :bookings
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :name, presence: true, uniqueness: true
  validates :address, :description, :price, :seats, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookings, only: [:show, :destroy]

  def my_bookings
    @my_bookings = Booking.where(user: current_user)
    authorize @my_bookings
  end

  def show
    @booking = current_user.booking
    @workspace = Workspace.find(params[:workspace_id])
  end

  def create
    # I need to find the event that we’re making a booking on
    @workspace = Workspace.find(params[:workspace_id])
    # and because the event “has_many :bookings”
    @booking = Booking.new(booking_params)
    @booking.workspace = @workspace
    # which person is booking the event
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to my_bookings_bookings_path, notice: 'Your booking was successfully requested.'
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_bookings_path, notice: 'Your booking was successfully cancelled.'
  end

 def validation
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to new_workspace_path, notice: 'You accepted the booking'
  end

  def rejection
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "rejected"
    @booking.save
    redirect_to new_workspace_path, notice: 'You rejected the booking'
  end



  private
  def set_bookings
    @booking = Booking.find(params[:id])
  end
  def booking_params
    params.require(:booking).permit(:workspace_id, :date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspace, only: [:edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR address ILIKE :query"
      @workspaces = policy_scope(Workspace.where(sql_query, query: "%#{params[:query]}%"))
    else
      @workspaces = policy_scope(Workspace)
    end

    #@flats = Flat.geocoded # returns flats with coordinates

    @markers = @workspaces.map do |workspace|
      {
        lat: workspace.latitude,
        lng: workspace.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { workspace: workspace })
      }
    end
  end

  def my_workspaces
    @my_workspaces = Workspace.where(user: current_user)
    authorize @my_workspaces
  end

  def show
    @workspace = Workspace.find(params[:id])
    @booking = Booking.new
    authorize @workspace
  end

  def new
    @workspace = Workspace.new
    authorize @workspace
  end

  def create
    @workspace = Workspace.new(workspace_params)
    @workspace.user = current_user
    Workspace.geocoded
    authorize @workspace

    if @workspace.save
      redirect_to new_workspace_path, notice: 'Your new workspace was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @workspace.update(workspace_params)
    redirect_to new_workspace_path
  end

  def destroy
    @workspace.destroy
    redirect_to new_workspace_path, notice: 'Your workspace was successfully deleted.'
  end

  def set_workspace
    @workspace = Workspace.find(params[:id])
    authorize @workspace
  end

  def workspace_params
    params.require(:workspace).permit(:name, :address, :description, :price, :seats, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<h1> MY BOOKINGS </h1>
<div class="cards-workspaces" id="my-bookings-cards">
    <% @my_bookings.each do |booking| %>
        <div class="card" id="my-bookings-card">
          <% if Workspace.find(booking.workspace_id).photo.present? %>
          <%= cl_image_tag Workspace.find(booking.workspace_id).photo.key, class: "card-image" %>
          <% else %>
          <%= image_tag 'workspace-01.png', class: "card-image"%>
          <% end %>
          <div class="card-content">
            <h2><%= Workspace.find(booking.workspace_id).name %></h2>
            <p>Address </br><strong><%= Workspace.find(booking.workspace_id).address %></strong></p>
            <p>Description </br><strong><%= Workspace.find(booking.workspace_id).description %></strong></p>
            <p id="price-wrapper"><span id="price"><%= Workspace.find(booking.workspace_id).price %>€</span> / Day</p>
            <p><span id="request-email"><%= booking.date %></span></p>
            <% if booking.status === "accepted" %>
                  <span class="request-status" id="accepted">Accepted</span>
              <% elsif booking.status === "rejected" %>
                  <span class="request-status" id="rejected">Rejected</span>
              <% else  %>
                  <span class="request-status" id="pending">Pending</span>
            <% end %>
            <%= link_to 'Delete', booking ,method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", id: "delete-btn"%>
          </div>
        </div>
    <% end %>
</div>

  <br>
  <div id = "link-top">
    <%= link_to "Find other workspaces", workspaces_path, class: "button-primary"%>
  </div>

  <br>
  <br>
  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flexdex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>

  <p class="alert"><%= alert %></p>

  <%= render 'shared/flashes' %>

</html>

app/views/pages/home.html.erb
<div class="header-wrapper">
<h1>ADIEU, HOME OFFICE.</br>HELLO, LIFE.</h1>
<p>Are you ready for new opportunities outside your home bubble? Discover your new Workspaces with FlexDex
- whenever you want, whereever you want and with who you want.</p>
<%= link_to "All Workspaces", workspaces_path, class: "button-primary", id:"header-btn"%>
<%= image_tag 'home-01.png', class: "header-image"%>
</div>

<%= image_tag 'background-vector.png', class: "background-vector-green"%>

<div class="second-wrapper">
  <div class="second-text">
    <h1>ENJOY</br>FLEXIBILITY.</h1>
    <p>FlexDex offers very flexible agreements. With the vitality of business, change is constant. Being in a shared workspace allows for adjustments to be made with increased ease and in an efficient manner.</p>
  </div>
<%= image_tag 'home-02.png', class: "second-image"%>
</div>

<div class="third-wrapper">
  <div class="third-text">
    <h1>CREATE</br>COLLABORATION.</h1>
    <p>FlexDex Working spaces expose you to chance and opportunity. Who knows where a casual conversation may lead? Working in proximity to others allows quick collaboration to occur. Next thing you know, you could be hiring someone new.</p>
  </div>
<%= image_tag 'home-03.png', class: "third-image"%>
</div>

<div class="fourth-wrapper">
  <div class="fourth-text">
    <h1>BOOST</br>CREATIVITY.</h1>
    <p>By working with other individuals and exposing yourself to new perspectives, coworking spaces can provide bursts of creativity. Sometimes, switching spaces and heading to a new office can allow you to refresh your mind and consider alternative solutions to business problems.</p>
  </div>
<%= image_tag 'home-04.png', class: "fourth-image"%>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-flexdex.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Discover Workspaces", workspaces_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Become a Host", new_workspace_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Workspace", new_workspace_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", my_bookings_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/workspaces/_form.html.erb
<%= simple_form_for(@workspace) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :seats %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.submit class: "button-primary", id:"create-btn"%>
  </div>
<% end %>

app/views/workspaces/_info_window.html.erb
<h2><%= workspace.name %></h2>
<p><%= workspace.address %></p>
<%= link_to 'Show', workspace , class: "button-primary", id: "show-btn"%>

app/views/workspaces/edit.html.erb
<h1>UPDATE YOUR WORKSPACE</h1>

<%= render 'form', workspace: @workspace %>

app/views/workspaces/index.html.erb
<h1>DISCOVER OUR </br>WORKSPACES</h1>

<div class="search-wrapper">
<%= form_tag workspaces_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    id: "searchfield",
    placeholder: "Find a workspace"
  %>
  <%= submit_tag "Search", class: "button-primary", id: "search-btn"%>
<% end %>
</div>

<div class="cards-workspaces">
    <% @workspaces.each do |workspace| %>
        <div class="card">
          <% if workspace.photo.present? %>
          <%= cl_image_tag workspace.photo.key, class: "card-image" %>
          <% else %>
          <%= image_tag 'workspace-01.png', class: "card-image"%>
          <% end %>
        <div class="card-content">
          <h2><%= workspace.name %></h2>
          <p>Address </br><strong><%= workspace.address %></strong></p>
          <p>Description </br><strong><%= workspace.description %></strong></p>
          <p id="price-wrapper"><span id="price"><%= workspace.price %>€</span> / Day</p>
          <% if workspace.user_id == current_user.id %>
            <%= link_to 'Your Workspace', workspace , class: "button-secondary", id: "my-btn"%>
          <% else %>
            <%= link_to 'Show', workspace , class: "button-primary", id: "show-btn"%>
          <% end %>
        </div>
        </div>
    <% end %>
</div>

<div class="map" id="map"
  style="height: 1250px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/workspaces/new.html.erb
<h1>MY WORKSPACES</h1>

<div class="cards-workspaces" id="my-workspaces-cards">
  <% current_user.workspaces.each do |workspace| %>
  <div class="card" id="my-workspaces-card">
    <% if workspace.photo.present? %>
          <%= cl_image_tag workspace.photo.key, class: "card-image" %>
          <% else %>
          <%= image_tag 'workspace-01.png', class: "card-image"%>
          <% end %>
    <div class="card-content">
      <h2 id="address"><%= workspace.name %></h2>
      <p>Address </br><strong><%= workspace.address %></strong></p>
      <% if workspace.bookings.present? %>
        <p id="requests">Requests for <%= workspace.name %>:</p>
          <ul> <% workspace.bookings.each do |booking| %>
            <li><div class="email-acceptance"><span id="request-email"><%= booking.user.email%></span>
              <% if booking.status === "accepted" %>
                  <span class="request-status" id="accepted">Accepted</span>
              <% elsif booking.status === "rejected" %>
                  <span class="request-status" id="rejected">Rejected</span>
              <% else  %>
                  <span class="request-status" id="pending">Pending</span>
              <% end %>
              </div>
              <p id="accept-reject"><%= link_to "Accept", validation_booking_path(booking)%>   <%= link_to "Reject", rejection_booking_path(booking) %></p>
              <% end %>
            </li>
          </ul>
        <% else %>
        <p id="requests">No Requests for <%= workspace.name %></p>
        <% end %>
     <%= link_to 'Edit', edit_workspace_path(workspace) , class: "button-primary", id: "edit-btn"%>
     <%= link_to 'Delete', workspace_path(workspace) ,method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning", id: "delete-btn"%>
  </div>
  </div>
<% end%>
</div>


<h2>Create a new workspace</h2>

<div class="card-create">
<%= render 'form', workspace: @workspace %>
</div>

app/views/workspaces/show.html.erb
<div class="book-workspaces">
<div class="card-show">
    <% if @workspace.photo.present? %>
      <%= cl_image_tag @workspace.photo.key, class: "card-image-show" %>
      <% else %>
        <%= image_tag 'workspace-01.png', class: "card-image-show"%>
    <% end %>
  <div class="card-content">
  <h1 class="ws-name-show"><%= @workspace.name %></h1>
  <p>Address </br><strong><%= @workspace.address %></strong></p>
  <p>Description </br><strong><%= @workspace.description %></strong></p>
  <p>Seats: <strong><%= @workspace.seats %></strong></p>
  </div>
  </div>
</div>

<div class="book-workspace">
  <h4><strong>Book this Workspace</strong></h4>
  <div>
  <%= simple_form_for [@workspace, @booking] do |f| %>
  <div class="text-form-book-ws">
     <%= f.input :date, as: :date %>
    <h4 class="price-show"><%= @workspace.price %> € / day</h4>
  </div>
    <%= f.submit class:"button-primary", id:"button-book-ws"%>
  <% end %>
  </div>
</div>

<%= link_to 'All Workspaces', workspaces_path, class:"button-secondary", id:"button-all-ws" %>

<br>
<br>
<br>